baseURL = 'https://thorgoesdevving.com/'
languageCode = 'en-us'
title = "Thor's website"
copyright = 'Copyright Thoricelli. All rights reserved.'

disableKinds = ['taxonomy', 'term']

[minify]
  minifyOutput = true

[minify.tdewolff.html]
  keepWhitespace = false
  keepComments = false

[params]
  author = 'thoricelli'

[outputs]
  home = ['html']

[markup.tableOfContents]
  startLevel = 1
  endLevel = 6


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    noClasses = false
    lineNumbersInTable = false
    style = "monokai"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$', '$']]
          inline = [['\(', '\)']]
      [markup.goldmark.extensions.typographer]
        disable = true